# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoodEatingFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoodEatingFireBase
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
end
